
server:
  port: 8000

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
 
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: green
    password: green1234
    url: jdbc:mariadb://localhost:3306/greendb?serverTimezone=Asia/Seoul
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create  # create, none
      naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true 

  mail:
    host: smtp.gmail.com
    port: 587
    username: eamailtest221222@gmail.com
    password: hgikuvxauhzsdiyd
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
